apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - sops-age-secret.yaml
secretGenerator:
  - name: sops-age
    files:
      - age.agekey
    options:
      disableNameSuffixHash: true
generatorOptions:
  disableNameSuffixHash: true
