apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure/metallb
  - ../../../infrastructure/ingress-nginx
  - ../../../infrastructure/monitoring
  - ../../../applications/secrets
  - ../../../applications/mysql
  - ../../../applications/wordpress
